# Generated by Django 2.2.9 on 2020-01-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200125_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
