# Generated by Django 2.2.9 on 2020-01-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200126_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='userwallet',
            field=models.IntegerField(default=0),
        ),
    ]
