# Generated by Django 2.2.9 on 2020-01-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200126_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='userwallet',
            new_name='wallet',
        ),
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
