# Generated by Django 2.2.9 on 2020-01-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200127_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='age',
        ),
        migrations.AddField(
            model_name='post',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='years',
            field=models.IntegerField(default=0),
        ),
    ]
