# Generated by Django 2.2.9 on 2020-01-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_remove_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
